version: "3.8"
services:
  nginx:
    image: nginx:ng1.0
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    restart: on-failure
    networks:
      - inception
    container_name: nginx
    env_file:
      - path: .env
    depends_on:
      - wordpress

  mariadb:
    image: mariadb:md1.0
    build: ./requirements/mariadb
    networks:
      - inception
    container_name: mariadb
    restart: on-failure
    expose:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - path: .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s

  wordpress:
    image: wordpress:wp1.0
    build: ./requirements/wordpress
    expose:
      - "9000:9000"
    networks:
      - inception
    restart: on-failure
    env_file:
      - path: .env
    volumes:
      - wordpress:/var/www/wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy

networks:
  inception:
    name: inception
    driver: bridge
  
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/$USER/data/wordpress
        
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/$USER/data/mariadb
  
