version: "3.8"
services:
  nginx:
    image: nginx:ng1.0
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - /var/www/html
    restart: on-failure
    networks:
      - inception
    container_name: nginx
    env_file:
      - path: .env
        required: true

  mariadb:
    image: mariadb:md1.0
    build: ./requirements/mariadb
    networks:
      - inception
    container_name: mariadb
    restart: on-failure
    expose:
      - "3306"
    volumes:
      - /home/gabrieltorres/data
    env_file:
      - path: .env
        required: true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s

  wordpress:
    image: wordpress:wp1.0
    build: ./requirements/wordpress
    expose:
      - "9000"
    networks:
      - inception
    restart: on-failure
    env_file:
      - path: .env
        required: true
    volumes:
      - /var/www/html
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy

networks:
  inception:
    name: inception
    driver: bridge
volumes:
  wordpress:
    driver: local
    driver_opts:
      device: /home/gabrieltorres/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      device: /home/gabrieltorres/data/mariadb
  