version: "3.8"
services:
  nginx:
    image: nginx:ng1.0
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - /var/www/html
    restart: on-failure
    networks:
      - inception
    container_name: nginx
    env_file:
      - path: .env
        required: true

  mariadb:
    image: mariadb:md1.0
    build: ./requirements/mariadb
    networks:
      - inception
    container_name: mariadb
    expose:
      - "3306"
    volumes:
      - /home/gade-alm/data
    env_file:
      - path: .env
        required: true



  wordpress:
    image: wordpress:wp1.0
    build: ./requirements/wordpress
    expose:
      - "9000"
    networks:
      - inception
    restart: on-failure
    volumes:
      - /var/www/html
    container_name: wordpress
    # depends_on:
    #   mariadb:
    #     condition: service_healthy


networks:
  inception:
    driver: bridge
volumes:
  wordpress:
    driver: local
  mariadb:
    driver: local
  