version: "3.8"
services:
  nginx:
    image: nginx
    build: ./srcs/requirements/nginx
    ports:
      - "443:80"
    volumes:
      - /var/www/html
    restart: on-failure
    networks:
      - inception
    container_name: nginx
  maria-db:
    image: mariadb
    build: ./srcs/requirements/mariadb
    networks:
      - inception
    container_name: mariadb
    expose:
      - "3306"
  wordpress:
    image: wordpress
    build: ./srcs/requirements/wordpress
    expose:
      - "9000"
    networks:
      - inception
    restart: on-failure
    volumes:
      - /var/www/html
    container_name: wordpress
networks:
  inception:
    driver: bridge