FROM debian:bullseye

# RUN apt-get update && apt-get -y upgrade -y  && apt-get install -y wget

# RUN 	

#apt-get install -y php php-bcmath php-curl php-imagick php-intl php-json php-mbstring php-mysql php-xml php-zip mariadb-client
#wget https://wordpress.org/wordpress-6.4.2.tar.gz -P /var/www
#cd /var/www
#tar -xvf wordpress-6.4.2.tar.gz 
#chown -R root:root /var/www/wordpress
